-- 부서
CREATE TABLE MY_SCHEMA.DEPT_EX (
	DEPTNO NUMBER(2)    NOT NULL, -- 부서번호
	DNAME  VARCHAR2(20) NOT NULL, -- 부서명
	LOC    VARCHAR2(20) NOT NULL  -- 위치
);

-- 부서 기본키
CREATE UNIQUE INDEX MY_SCHEMA.PK_DEPT_EX
	ON MY_SCHEMA.DEPT_EX ( -- 부서
		DEPTNO ASC -- 부서번호
	);

-- 부서
ALTER TABLE MY_SCHEMA.DEPT_EX
	ADD
		CONSTRAINT PK_DEPT_EX -- 부서 기본키
		PRIMARY KEY (
			DEPTNO -- 부서번호
		);

-- 부서
COMMENT ON TABLE MY_SCHEMA.DEPT_EX IS '부서';

-- 부서번호
COMMENT ON COLUMN MY_SCHEMA.DEPT_EX.DEPTNO IS '부서번호';

-- 부서명
COMMENT ON COLUMN MY_SCHEMA.DEPT_EX.DNAME IS '부서명';

-- 위치
COMMENT ON COLUMN MY_SCHEMA.DEPT_EX.LOC IS '위치';

-- 부서 기본키
COMMENT ON INDEX MY_SCHEMA.PK_DEPT_EX IS '부서 기본키';

-- 부서 기본키
COMMENT ON CONSTRAINT MY_SCHEMA.DEPT_EX.PK_DEPT_EX IS '부서 기본키';

-- 사원정보
CREATE TABLE MY_SCHEMA.EMP_EX (
	EMPNO    NUMBER(4)    NOT NULL, -- 사원번호
	ENAME    VARCHAR2(20) NOT NULL, -- 사원명
	JOB      VARCHAR2(20) NOT NULL, -- 직업
	MGR      NUMBER(4)    NOT NULL, -- 매니저
	HIREDATE DATE         NOT NULL, -- 입사일
	SAL      NUMBER(7, 2) NOT NULL, -- 급여
	COMM     NUMBER(7, 2) NOT NULL, -- 성과급
	DEPTNO   NUMBER(2)    NULL      -- 부서번호
);

-- 사원정보 기본키
CREATE UNIQUE INDEX MY_SCHEMA.PK_EMP_EX
	ON MY_SCHEMA.EMP_EX ( -- 사원정보
		EMPNO ASC -- 사원번호
	);

-- 사원정보
ALTER TABLE MY_SCHEMA.EMP_EX
	ADD
		CONSTRAINT PK_EMP_EX -- 사원정보 기본키
		PRIMARY KEY (
			EMPNO -- 사원번호
		);

-- 사원정보
COMMENT ON TABLE MY_SCHEMA.EMP_EX IS '사원정보';

-- 사원번호
COMMENT ON COLUMN MY_SCHEMA.EMP_EX.EMPNO IS '사원번호';

-- 사원명
COMMENT ON COLUMN MY_SCHEMA.EMP_EX.ENAME IS '사원명';

-- 직업
COMMENT ON COLUMN MY_SCHEMA.EMP_EX.JOB IS '직업';

-- 매니저
COMMENT ON COLUMN MY_SCHEMA.EMP_EX.MGR IS '매니저';

-- 입사일
COMMENT ON COLUMN MY_SCHEMA.EMP_EX.HIREDATE IS '입사일';

-- 급여
COMMENT ON COLUMN MY_SCHEMA.EMP_EX.SAL IS '급여';

-- 성과급
COMMENT ON COLUMN MY_SCHEMA.EMP_EX.COMM IS '성과급';

-- 부서번호
COMMENT ON COLUMN MY_SCHEMA.EMP_EX.DEPTNO IS '부서번호';

-- 사원정보 기본키
COMMENT ON INDEX MY_SCHEMA.PK_EMP_EX IS '사원정보 기본키';

-- 사원정보 기본키
COMMENT ON CONSTRAINT MY_SCHEMA.EMP_EX.PK_EMP_EX IS '사원정보 기본키';

-- 사원정보
ALTER TABLE MY_SCHEMA.EMP_EX
	ADD
		CONSTRAINT FK_DEPT_EX_TO_EMP_EX -- 부서 -> 사원정보
		FOREIGN KEY (
			DEPTNO -- 부서번호
		)
		REFERENCES MY_SCHEMA.DEPT_EX ( -- 부서
			DEPTNO -- 부서번호
		);

-- 부서 -> 사원정보
COMMENT ON CONSTRAINT MY_SCHEMA.EMP_EX.FK_DEPT_EX_TO_EMP_EX IS '부서 -> 사원정보';